"use client"
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/global.scss";
import { Providers } from "@/redux/providers";

import { Baloo_Bhai_2 } from "next/font/google";
import MainLayout from "@/components/MainLayout";
import { usePathname } from "next/navigation";

const balooBhai = Baloo_Bhai_2({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-baloo",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const isAuthPage = pathname === '/login';
  return (
    <html lang="en">
      <body className={`${balooBhai.className} ${geistSans.variable} ${geistMono.variable}`}>
        <Providers>
          {isAuthPage ? children : <MainLayout>{children}</MainLayout>}
        </Providers>
      </body>
    </html>
  );
}
